import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import CustomCursor from "./utils/CustomCursor";
import { AnimatedBackground } from "./utils/AnimatedBackground";

// // Lazy load non-critical components that don't need SSR
// const CustomCursor = dynamic(() => import("@/app/utils/CustomCursor"), {
//   ssr: false,
// });

// const AnimatedBackground = dynamic(
//   () =>
//     import("@/app/utils/AnimatedBackground").then((mod) => ({
//       default: mod.AnimatedBackground,
//     })),
//   {
//     ssr: false,
//   }
// );

// Optimize font loading with next/font - eliminates render-blocking
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-playfair-display",
  display: "swap",
  preload: true,
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-inter",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Pranjal Gupta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${inter.variable}`}>
      <body>
        <CustomCursor />
        <div className="children-layout">{children}</div>
        <AnimatedBackground />
      </body>
    </html>
  );
}
