import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./Navbar";

export const metadata: Metadata = {
  title: "Pranjal Gupta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="h-full p-8"> {children}</div>
      </body>
    </html>
  );
}
